### ISSUE TITLE
Will it be possible to use the mv3 version of the extension as the basis for my ad blocker, just like in mv2 and how?

### ISSUE THREAD

**Issue by Eugene706** [AdguardTeam/AdGuardMV3#13]

**Comment by 105th** [comment]
@Eugene706 Yes, I think it is possible because the license is the same as in the MV2 extension
we updated the license, you can read it here  - https://github.com/AdguardTeam/AdGuardMV3/blob/master/LICENSE

**Comment by Eugene706** [comment]
Is there any instruction on how to set your own rules for the extension? Like this in MV2 - https://github.com/AdguardTeam/AdguardBrowserExtension/blob/master/Extension/api/sample-extension/adguard-api.md

**Comment by Rutuj-Runwal** [comment]
> @105th Is there any instruction on how to set your own rules for the extension? Like this in MV2 - https://github.com/AdguardTeam/AdguardBrowserExtension/blob/master/Extension/api/sample-extension/adguard-api.md

MV3 uses declarativeNet Request and every rule has a unique id and rules with duplicate id's are not allowed so the method to declare them will be programmatically a little different. You can however add rules for the settings/options page directly

**Comment by Eugene706** [comment]
@Rutuj-Runwal I thought only network rules use declarativeNetRequest

**Comment by Rutuj-Runwal** [comment]
> @Rutuj-Runwal I thought only network rules use declarativeNetRequest

Yes only network rules are governed by declarativeNetRequest. Cosmetic filters are handled separately and they follow the rules mentioned in the link that I shared in the discussion above.

**Comment by Eugene706** [comment]
@Rutuj-Runwal My question was to which function in the code of the extension I need to pass these rules in order to see the result of their execution on the page

**Comment by 105th** [comment]
@Eugene706 we decided to separate the work with Chrome Declarative API in our open library - [tswebextension](https://www.npmjs.com/package/@adguard/tswebextension)

So you only need to pass the configuration there (with declarative rule sets included, which are prepared when the extension is built) - https://github.com/AdguardTeam/AdGuardMV3/blob/master/src/background/tswebextension.ts#L40

Also, if you want to change the static filter rules, check the following https://github.com/AdguardTeam/AdGuardMV3/blob/master/README.md#for-filters-maintainers (step 4)
