### ISSUE TITLE
overcoming the 30000 rules limit

### ISSUE THREAD

**Issue by 424344** [AdguardTeam/AdGuardMV3#14]
Since with MV3 each extension has a 30000 rules limit is it feasible to just "split" the extension into two different extensions?
You'll create an extension for blocking ads, and another one for blocking trackers.
Each extension will use up to 30000 rules, so a total of 60000 rules.

**Comment by 105th** [comment]
In fact, the total limit for all installed MV3 extensions is 300,000 rules. Thus, if two extensions are installed, the limit will be 150,000 for each of them.

**Comment by 424344** [comment]
Here I've read that the limit is 30000 per extension, and a total of 330000:
https://adguard.com/en/blog/adguard-mv3.html
But maybe I misunderstood.

**Comment by 105th** [comment]
@424344 By 300,000 rules I meant 330,000, of course you're right. 330,000 rules is the total limit for all installed extensions. And for each extension at least 30,000 rules are guaranteed (I believe that until the total limit is exhausted)

**Comment by ameshkov** [comment]
30k is a guaranteed limit per extension. 300k is a "shared" limit for all extensions.

**Comment by ameshkov** [comment]
30k is a guaranteed limit per extension. 300k is a "shared" limit for all extensions.
