### ISSUE TITLE
Settings options do not display intended description

### ISSUE THREAD

**Issue by Rutuj-Runwal** [AdguardTeam/AdGuardMV3#15]
The options in settings menu shows: "options_block_ads_option" instead of "Block Ads" string.
<br />
Refer the image below->
<br />
![image](https://user-images.githubusercontent.com/59436520/193393576-fed59910-954b-4374-8707-b700ccb6e0f5.png)

**Comment by ameshkov** [comment]
Could you please tell us what system language do you have?

**Comment by ameshkov** [comment]
Ah nvm I see

**Comment by maximtop** [comment]
@Rutuj-Runwal can you try to reload the extension or browser? I wasn't able to reproduce on my side

**Comment by maximtop** [comment]
Also, I think that reinstall should help you.

**Comment by Birbber** [comment]
@Rutuj-Runwal Fixed in v0.3.13. Please check.

**Comment by Rutuj-Runwal** [comment]
> @Rutuj-Runwal Fixed in v0.3.13. Please check.

Yes the issue has now been fixed.
Thanks
