### ISSUE TITLE
Delayed execution of scripts

### ISSUE THREAD

**Issue by 424344** [AdguardTeam/AdGuardMV3#18]
I'm currently testing both adguard and ublock lite ( https://chrome.google.com/webstore/detail/ublock-origin-lite/ddkjiahejlhfcafbddmgiahcphecmpfh ) and found that ublock lite blocks youtube ads, while adguard does not.
I'm talking about youtube ads at the start of videos, and that you can skip after 5 seconds.
Please can you add support for blocking youtube ads?
Thanks.

**Comment by ameshkov** [comment]
AG does block them, but due to the service worker issues in some cases (when the service worker is killed and you open YT at the same time, or when you open YT right on the browser startup) the blocking may not occur. In this case it'd be enough to reload the YT tab.

Note, that this is a temporary limitation that will be gone when MV3 implementation is out of the prototype stage.

**Comment by 424344** [comment]
I've tried loading the youtube tab multiple times but it didn't block the ads (tested on edge v106)
the link I tested is this one:
https://www.youtube.com/watch?v=Ks_Cp9XL-XQ

screenshot:
![image](https://user-images.githubusercontent.com/26486758/196054237-3dda2cbc-90f6-4123-8bbc-6d52650adec9.png)

**Comment by ameshkov** [comment]
Weird, let us doublecheck just in case.

**Comment by marcoclg19** [comment]
I also have the same problem (Chrome v107)... ads on YT are not blocked.

**Comment by 105th** [comment]
Tested with our extension version 0.3.13 in Chrome 106: fails to repeat the problem with video ads. 
@424344 @marcoclg19 Can you check that our extension has the latest update and that filters are enabled in the extension settings?

**Comment by marcoclg19** [comment]
I re-installed the extension and activated all filters, but it still does not block the ads.

**Comment by 424344** [comment]
still not working for me.
I'm using windows in italian, maybe locale can have some impact on ads?

**Comment by marcoclg19** [comment]
> still not working for me. I'm using windows in italian, maybe locale can have some impact on ads?

I also have Italian as my main language...

**Comment by 105th** [comment]
@marcoclg19 @424344 We were finally able to reproduce the problem and fixed it in version 0.3.14. We sent the new version to the Chrome Store for review. It usually takes a few days to review

**Comment by 105th** [comment]
@424344 @marcoclg19 v0.3.14 just published (https://chrome.google.com/webstore/detail/adguard-adblocker-mv3-exp/apjcbfpjihpedihablmalmbbhjpklbdf).
Could you please try this version and tell us the results of the blocking on the YouTube?

**Comment by marcoclg19** [comment]
@105th I've just tried it... I have opened about 20 YT videos and I haven't seen a single ads and it even seems to load faster. 
I don't know how to thank you and the team :)

**Comment by 105th** [comment]
@marcoclg19 great news, glad to hear it!

**Comment by 424344** [comment]
yes,  it's working for me too.
thanks.
