### ISSUE TITLE
git link wrong on chrome web store page

### ISSUE THREAD

**Issue by tenapps2** [AdguardTeam/AdGuardMV3#19]
on chrome webstore page for adguard mv3 extension:
https://chrome.google.com/webstore/detail/adguard-adblocker-mv3-exp/apjcbfpjihpedihablmalmbbhjpklbdf

in the description there is a link to the issues site, that I believe is wrong:
https://github.com/AdGuardTeam/AdGuardBrowserExtension/issues

I think it should point to this repository instead:
https://github.com/AdguardTeam/AdGuardMV3/issues

**Comment by 105th** [comment]
Oh, yes, thank you for writing.
We'll fix that now.

**Comment by 105th** [comment]
Fixed, thanks for the report 👍

**Comment by tenapps2** [comment]
hello, on chome web store I still see the wrong link.

**Comment by 105th** [comment]
@tenapps2 here's what I see:
<img width="967" alt="screenshot" src="https://user-images.githubusercontent.com/11395678/202847740-1e4bad46-d55c-4634-a3bd-d8e915defacc.png">

**Comment by 424344** [comment]
ok maybe I have a problem with the cache of my browser.
thank you.

**Comment by krystian3w** [comment]
Check translations?

https://chrome.google.com/webstore/detail/adguard-adblocker-mv3-exp/apjcbfpjihpedihablmalmbbhjpklbdf?hl=pl
