### ISSUE TITLE
ENHANCEMENT Option (user switch) to block opening new windows which are not user initiated

### ISSUE THREAD

**Issue by LennyFox** [AdguardTeam/AdGuardMV3#23]
Reason for requesting:  Minimalizing the number of extensions used to stay under the 330.000 rules limit

Since MV3 extensions have a guaranteed quota of 30.000 static rules and 5000 dynamic rules. All extensions together may use 330.000 rules. To block irritating popups which are not triggered by the user, I currently use AdGuard's Popup Blocker script [https://github.com/AdguardTeam/PopupBlocker](url)

Would it be possible to add a switch in the adguard to add this script functionality on a per website basis? 
This would reduce the number of specific rules to block pop-ups and new window creation (pop-unders) often used by annoying advertising networks (e.g. traffucjunky uses this mechanism). 

![image](https://user-images.githubusercontent.com/63356355/198874758-6435582d-0fd5-44cd-a8d3-208803c93098.png)

This would have the benefit for AdGuard users not needing extensions which are directed to blocking popups.

**Comment by ameshkov** [comment]
> This would reduce the number of specific rules to block pop-ups and new window creation (pop-unders) often used by annoying advertising networks (e.g. traffucjunky uses this mechanism).

Well, rather good news is that the rules that are used against pop-ups are mostly "cosmetic", i.e. they don't count against the declarative rules limit anyways.
