### ISSUE TITLE
ENHANCEMENT Option to minimize rules usage

### ISSUE THREAD

**Issue by LennyFox** [AdguardTeam/AdGuardMV3#24]
Hi,

I am a happy user of your free DNS where a part of the blocking is handled.

I am using Adguard MV3 with ad-blocking only and added the "tracking servers" of AdGuard's Spyware filters (which just fits).

Would it be possible to add two options in the settings
1. Use optimized filters
2. Use bare bone filters e.g. for Base filter this would be the generic filters and the allow list to prevent website breakage
 - https://github.com/AdguardTeam/AdguardFilters/blob/master/BaseFilter/sections/adservers.txt
 - https://github.com/AdguardTeam/AdguardFilters/blob/master/BaseFilter/sections/antiadblock.txt
 - https://github.com/AdguardTeam/AdguardFilters/blob/master/BaseFilter/sections/banner_sizes.txt
 - https://github.com/AdguardTeam/AdguardFilters/blob/master/BaseFilter/sections/general_elemhide.txt
 - https://github.com/AdguardTeam/AdguardFilters/blob/master/BaseFilter/sections/general_extensions.txt
 - https://github.com/AdguardTeam/AdguardFilters/blob/master/BaseFilter/sections/general_url.txt
 - https://github.com/AdguardTeam/AdguardFilters/blob/master/BaseFilter/sections/allowlist.txt

I think that users of AdGuard DNS (with blocking at DNS side) don't need first party blocking (I guess the DNS filters do that).  Also AG MV3 has an option to block adds (visor crossshair icon) and block simple stuff themselves. Combining AG's DNS and the extension this (using more generic rules and add block rules yourself) makes more sense to me.

**Comment by ameshkov** [comment]
Well, with MV3 we're very limited in the ways what versions of the filter lists can be built-in. That's why the "Use optimized filters" option from the MV2 extension or using different versions of the lists dynamically is technically not possible at this point.
