### ISSUE TITLE
Not an issue, but 2 questions

### ISSUE THREAD

**Issue by Gandalf-The-Wise** [AdguardTeam/AdGuardMV3#25]
I see that version 0.3.15 is now out.
Wat are the changes?
As I understand for updating the filters an MV3 extension must be updated.
What are your plans for that?
Are we going to get more releases?

**Comment by SampeiNihira** [comment]
Hi.
Yes,in my opinion for updating the filter lists:

https://github.com/AdguardTeam/AdGuardMV3/commit/24e3736df38dd815392d1c07103f6a92393a9316

**Comment by Kees1958** [comment]
@Gandalf-The-Wise my friend, you are actually asking three questions (in stead of two) :-) 
1. Wat are the changes?
2. What are your plans for that?
3. Are we going to get more releases?

regards

Kees

**Comment by Birbber** [comment]
Hello! Sorry for the late reply.
The MV3 extension comes with a hardcoded set of filters and rules. Currently it's impossible to update the rules separately.
[Here](https://github.com/w3c/webextensions/issues/162#issuecomment-1309390759) we are discussing adding this to MV3 through the mechanism of partial rule updates. Now it's not clear how exactly we'll use this, but there's a slight possibility that the button for updating filters may appear.
