### ISSUE TITLE
Unable to access options

### ISSUE THREAD

**Issue by SampeiNihira** [AdguardTeam/AdGuardMV3#28]
AdGuard MV3 0.3.16
Edge v.107.X
Windows 10 Home

![1](https://user-images.githubusercontent.com/44166263/202457816-07e9e6f6-416a-425d-b133-f1312f1cef65.jpg)

The problem was not present in the previous build.

**Comment by 105th** [comment]
@SampeiNihira working on it right now. a fix will be available as soon as Chrome checks, usually in 1-2 days.

**Comment by 105th** [comment]
The version with the fix has now been sent to the Chrome Web Store for review
Waiting for the review

**Comment by SampeiNihira** [comment]
Problem solved with build 0.3.17.
TH.

**Comment by 105th** [comment]
Yes, Chrome reviewed the extension a couple of hours ago.
