### ISSUE TITLE
Delay when blocking elements.

### ISSUE THREAD

**Issue by Mercyletter** [AdguardTeam/AdGuardMV3#32]
AdGuard MV3 0.3.18
Edge v.108.X
Windows 10 Pro

I am observing that the extension has a delay when blocking, I attach screenshots.

![1MV3](https://user-images.githubusercontent.com/32906745/210329680-15110705-5a94-461c-9333-d1bca46f4ebf.jpg)
![2MV3](https://user-images.githubusercontent.com/32906745/210329701-eb0b86c4-5499-4ac3-aca9-da9a21963143.jpg)

**Comment by Mercyletter** [comment]
Maybe adding this option could be a solution but I don't know because I'm not an advanced user.
Disable site pre-loading (prevents any connection for blocked network requests)

**Comment by ameshkov** [comment]
This is a known issue of the prototype, this behavior will be greatly improved later when the MV3 engine will be closer to the release.
