### ISSUE TITLE
issue on uprot.net

### ISSUE THREAD

**Issue by tortino2** [AdguardTeam/AdGuardMV3#35]
issue on this page:
https://uprot.net/msfi/RUV5cnlleENOU0EzTTBOYTRSM1Vwdz09

when adblock is enabled the "continue" button is not visibile.

**Comment by Birbber** [comment]
Hello! Sorry for the late response. Is this issue still reproducible?
We weren't able to reproduce it — "continue" button is visible in any case. What filters did you enable?

**Comment by tortino2** [comment]
hello,
with latest version the bug is resolved.
you can close this issue.
thank you!
