### ISSUE TITLE
Long wait times between filter updates

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardMV3#36]
The most recent update to the filters was [yesterday](https://github.com/AdguardTeam/AdGuardMV3/commit/9e1df624f80c69fecab3a669315b1b37935c4213), and the one prior being [December 28](https://github.com/AdguardTeam/AdGuardMV3/commit/96000da79b5e06930254e2a8a9cf1d533898db38).

The MV3 extension is my only option on corporate devices as the firewall has blocked the adtidy domain, so it would be good to get some form of routine filter update.
I understand that it takes time for updates to be approved on the Chrome Store, but could the filter updates be more routine, or is there another reason why there's an inconsistency?

**Comment by maximtop** [comment]
We plan to automatically update the extension in the future, but this is not our top priority at the moment.

**Comment by maximtop** [comment]
We have started to update the extension and filters once a week. So I think this issue can be closed.
