### ISSUE TITLE
Feature request: not an issue - why does not use AdGuard its Unique Selling Points?

### ISSUE THREAD

**Issue by Kees1958** [AdguardTeam/AdGuardMV3#39]
With Mv3 Google imposed a maximum rule count per extension and one for all extensions.

AdGuard has an enormous advantage over other adblocking extensions, because it
1. Maintains its own filters (I like the Adguard Mv2 optimized filters option)
2. offers a DNS service also

All the rules of Adguard DNS and for instant OISD large can be removed from the AdGuard 'super optimized' ruleset in AdGuardMv3.  This would probably reduce the AdGuard Mv3 rule count dramatically. 

I am testing this option at the moment using
1. AdGuard DNS (see picture below)
2. AdGuard MV3 with only two filter lists:
https://raw.githubusercontent.com/Kees1958/W3C_annual_most_used_survey_blocklist/master/EU_US_MV3_most_common_ad%2Btracking_networks.txt
https://raw.githubusercontent.com/LennyFox/Blocklists/master/news_websites.txt

![image](https://user-images.githubusercontent.com/30925856/230851970-523ce60f-db33-4ac5-bb1c-5bbd1bbc2fa6.png)

**Comment by SampeiNihira** [comment]
Hi Kees1958.
What lists (AdGuard DNS) did you enter in Bocklists?

**Comment by Kees1958** [comment]
![image](https://user-images.githubusercontent.com/30925856/231555026-1351c28c-5e3e-421c-acef-1d8c468615d6.png)

And in user rules, I basically entered (from LennyFox)
https://github.com/LennyFox/Blocklists/blob/master/Block_non_latin_TLDs.txt
https://github.com/LennyFox/Blocklists/blob/master/Block_TLDs_with_bad_reputation.txt
https://github.com/LennyFox/Blocklists/blob/master/Warn_for_countries_with_bad_reputation.txt

**Comment by SampeiNihira** [comment]
@Kees1958

I use Next DNS so I set up TLD blocking directly there.
These are my user rules:

```
||*^$ping,object
||*^csp
||*^$third-party,denyallow=com|eu|inf|io|ms|net|it|org|edu

youtube.com##+js(set, ytInitialData.topbar.desktopTopbarRenderer.interstitial.consentBumpRenderer.forceConsent, false)
youtube.com##+js(json-prune, [].response.topbar.desktopTopbarRenderer.interstitial.consentBumpRenderer)
youtube.com##+js(json-prune, topbar.desktopTopbarRenderer.interstitial.consentBumpRenderer)
youtube.com##+js(set, ytInitialData.onResponseReceivedEndpoints, undefined)
youtube.com##+js(set, ytInitialData.topbar.desktopTopbarRenderer.interstitial.consentBumpV2Renderer, undefined)
youtube.com##+js(json-prune, [].response.overlay.consentBumpV2Renderer topbar.desktopTopbarRenderer.interstitial.consentBumpV2Renderer overlay.consentBumpV2Renderer response.overlay.consentBumpV2Renderer)
youtube.com##+js(set, ytInitialData.desktopTopbar.desktopTopbarRenderer.interstitial.consentBumpV2Renderer, undefined)

@@discordapp.com
@@ibb.co
@@supervideo.tv
@@serversicuro.cc
@@hdmario.live
@@postimg.cc
@@obi.de
@@pcdn.co
@@js.media-lab.ai
@@guardahd.stream
||browser.sentry-cdn.com

```

As you can see I use AdGuard MV3 in Hard Mode + TLD's.

**Comment by Kees1958** [comment]
Thx
