### ISSUE TITLE
hitomi.la is broken only by MV3 Extension

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/AdGuardMV3#4]
URL: `hitomi.la` [NSFW]
Issue: full breakage:

<details>
<summary>Screenshot</summary>

![hitomi](https://user-images.githubusercontent.com/58900598/187980710-af00c6f9-81f7-4c09-8f18-643f9a50dc40.png)

</details>

Details: some requests not blocked by stable extension seems to be blocked including `https://ltn.hitomi.la/gg.js` and `https://ltn.hitomi.la/feed-icon-14x14.png`. This happens only if Block Ads option is turned on.

Environment: Brave 1.42.97 (Chromium: 104.0.5112.102) Brave shield is globally turned off
AG Version 0.3.11

**Comment by Birbber** [comment]
Hello! Sorry for the late reply. Is this problem still relevant?

This issue wasn't reproduced on v0.3.33 in Chrome. As this extension is an experimental one we currently support it on Chrome only, and there might be issues in other browsers.
We can try reproducing it with the exact set of filters if you share it with us, and you can check if it's reproducible in Chrome.

**Comment by Yuki2718** [comment]
This was a specific case of #6 and I don't see breakage on 0.3.34.
