### ISSUE TITLE
In `README`, logo is hard to see when using dark theme in GitHub

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdGuardMV3#46]
In the [README](https://github.com/AdguardTeam/AdGuardMV3#readme), the logo is hard to see when using the dark theme on GitHub. You need to add a logo option for the dark theme.

Useful link: https://github.blog/changelog/2021-11-24-specify-theme-context-for-images-in-markdown/

<details><summary>Screenshot:</summary>

![image](https://github.com/AdguardTeam/AdGuardMV3/assets/19418601/66df04bb-23f8-4265-8c2a-1a4a77de7625)

</details>

**Comment by Birbber** [comment]
Hello, the logo has been fixed. I'm closing this issue.
