### ISSUE TITLE
Infinite new empty boxes on a page.

### ISSUE THREAD

**Issue by 0ABDL0** [AdguardTeam/AdGuardMV3#5]
I was testing MV3 for the Annoyances/Anti-Adblock detection of the sites on on a2zapk.com I knew that they constantly modified their Adblocker Detection process so when I went on a random download, I saw the Adguard icon go from 10 to 300+ in a few seconds, then seeing the scroll bar get smaller I realized something was wrong, when I do scroll down though. it's just empty boxes. never ending amount of them.

https://a2zapk.com/1253654-youtube-revanced-17-33-42-non-root-rvp-2-49-0-a2z.html pressing the download from here starts the process of the Adguard counter going wild with tons of blank squares on the page starting at the bottom

It also generally slows down that tab a lot and the loading page that requires the anti-adblocking measures to be defused doesn't load so maybe a two for one bug.

**Comment by 0ABDL0** [comment]
I'd also like to add that I don't recommend using this site or anything similar to download and use files from it as these sites aren't exactly verified in any way so its a risky adventure, it was just a site I knew because of their Adblock Prevention measures.

**Comment by alexx7311** [comment]
Hello! We'll close the ticket for now, if the problem recurs you can reopen it.
