### ISSUE TITLE
Ads not blocked on Facebook because of CSP

### ISSUE THREAD

**Issue by lam4o** [AdguardTeam/AdGuardMV3#57]
Ads are not blocked, console error:

VM386:6 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src *.facebook.com *.fbcdn.net blob: data: 'self' 'wasm-unsafe-eval' *.whatsapp.com whatsapp.com *.whatsapp.net whatsapp.net". Either the 'unsafe-inline' keyword, a hash ('sha256-jSi2nXUkxgGA/taLjbm2Q7sLNhJRhC7cSyQsArqrAcX='), or a nonce ('nonce-...') is required to enable inline execution.

**Comment by alexx7311** [comment]
@lam4o Hello! Please report this website via the extension popup. You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/

It is likely that this problem can be solved by filters.

**Comment by AdamWr** [comment]
I think that the problem is not related to filters, but to the fact that some JavaScript rules cannot be executed, because are blocked by website Content Security Policy.
Similar issue occurs in extension for Firefox - https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1733

**Comment by lam4o** [comment]
I initially posted the issue for the experimental MV3 version on chrome, but I can confirm ads are not blocked on Firefox too with the current MV2 version:

![image](https://github.com/AdguardTeam/AdGuardMV3/assets/8136494/48017340-6cc2-4a96-9b6b-2cea39a3d068)

Strangely, there are no problems with the current MV2 version on chrome

**Comment by lam4o** [comment]
That's the console log for MV3 on Chrome, a CSP issue indeed:

![image](https://github.com/AdguardTeam/AdGuardMV3/assets/8136494/befe3eee-c968-4bb7-950a-518422376972)
