### ISSUE TITLE
ads in outlook not blocked

### ISSUE THREAD

**Issue by lazymonkey2** [AdguardTeam/AdGuardMV3#58]
I'm using AdGuard MV3 0.4.22 on windows 10 x64. 
In the settings I have enabled all the 4 types of blocking.
In Microsoft web email (outlook.live.com) the ads in the inbox are not hidden:

![image](https://github.com/AdguardTeam/AdGuardMV3/assets/26486758/609488f9-52c1-4a47-ac56-87745284459e)

**Comment by alexx7311** [comment]
@lazymonkey2 Hello! Please report this website via the extension popup. You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/
