### ISSUE TITLE
Ads are not being blocked in YouTube embeds

### ISSUE THREAD

**Issue by trlkly** [AdguardTeam/AdGuardMV3#60]
While adblocking on the main YouTube site works fine, it seems that blocking ads on embedded YouTube videos is not. 

I would have maybe expected that you'd get the ad block warning, but the ads just play. 

It seems odd that such a popular site would not have been reported already, so I hope I'm not posting in the wrong place.

**Comment by trlkly** [comment]
On Patreon, I notice it's even weirder. Any page that contains a YouTube video gets constantly refreshed. The page gets reloaded, even if I turn off adblocking for Patreon.com. Only disabling the extension entirely fixes this.

**Comment by alexx7311** [comment]
@trlkly Hello! We need to get our filters team to look at this first. Please report the problem via the extension popup. 
<details>
  <summary>Screenshot</summary>

  ![Screenshot](https://github.com/AdguardTeam/AdGuardMV3/assets/114913601/2900208b-f8f3-41f3-a370-83c71515a50b)

</details>

I haven't been able to reproduce the problem yet. Found Patreon https://www.patreon.com/californialuv84 and scrolled down to the free video `✨VIDEO FOR PATRONS✨ LE SSERAFIM [LENIVERSE] EP. 1 & 2 "Welcome to the LENIVERSE" Reaction!`

I didn't see any constant refreshes, nor did I see any ads. When you report the problem, please specify all filters you use.

**Comment by trlkly** [comment]
Whenever I've encountered the constant refreshing, I've never merely scrolled down, always actually open the link below the video to see the whole post. . I don't even have to try to play the video--the page just literally goes into a refresh loop, though I can stop it. 

And either way, I still get ads if it's a YouTube embed.
