### ISSUE TITLE
Advertisements not blocked on youtube.com

### ISSUE THREAD

**Issue by devashishkatoriya** [AdguardTeam/AdGuardMV3#61]
Observing in-videos are still showing on youtube.com 

Thanks in advance ✌🏻

**Comment by alexx7311** [comment]
@devashishkatoriya Hello! Please report the problem via the extension popup. 
<details>
  <summary>Screenshot</summary>

  ![Screenshot](https://github.com/AdguardTeam/AdGuardMV3/assets/114913601/2900208b-f8f3-41f3-a370-83c71515a50b)

</details>

You can find step-by-step instructions at https://adguard.app/kb/guides/report-website/
