### ISSUE TITLE
User rules not applying on reload

### ISSUE THREAD

**Issue by stevehoek** [AdguardTeam/AdGuardMV3#63]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

Just trying the MV3 version for the first time.  Happy to see there is still an element picker.  On my local network router page http://192.168.0.1 I set up 3 user rules via element picker.  However, when I reload the page the rules don't apply (stick).

**Comment by alexx7311** [comment]
@stevehoek Hello! The element picker doesn't always create the proper selectors for blocking an element, it may be worth creating a rule manually.

You can learn how to do it by reading our article at https://adguard.info/kb/general/ad-filtering/create-own-filters/.
