### ISSUE TITLE
Gmail issues

### ISSUE THREAD

**Issue by YesTrustMe** [AdguardTeam/AdGuardMV3#64]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard MV3 Extension version

0.4.60

### Browser version

Chrome

### OS version

126.0.6478.63

### Filters enabled

Block ads, Block annoyances, Block trackers, English

### Issue Details

Lately having issues with Gmail and other sites (never had before). I disabled Adguard with them but in particular Gmail delete feature isn't working with latest version of Adguard.

### Expected Behavior

To work like in the past

### Actual Behavior

Gmail delete feature isn't working with latest version of Adguard.

**Comment by alexx7311** [comment]
@YesTrustMe Hello! Please describe step by step how to reproduce the problem.

**Comment by alexx7311** [comment]
@YesTrustMe Any updates? We cannot reproduce the problem with Gmail delete feature.

**Comment by YesTrustMe** [comment]
Hi. Issue was not in fact with Adguard, but another extension.
