### ISSUE TITLE
5.01 Beta is the same as non-beta

### ISSUE THREAD

**Issue by YesTrustMe** [AdguardTeam/AdGuardMV3#66]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard MV3 Extension version

5.01

### Browser version

Chrome 126.0.6478.127

### OS version

Windows 11

### Issue Details

Compared with the non-beta, even icon is same
1.
2.
3.

### Expected Behavior

same as old beta version

### Actual Behavior

same as non-beta

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by YesTrustMe** [comment]
I should add that even the icon has changed from black to green, If the beta version is now obsolete, remove it from the store please.

**Comment by vozersky** [comment]
@YesTrustMe Hi. The beta has replaced the prototype in the [Chrome WebStore](https://chromewebstore.google.com/detail/adguard-adblocker-mv3-exp/apjcbfpjihpedihablmalmbbhjpklbdf) and will stay available there.

With the full release, the MV3 version will become the main one and [replace our old extension](https://chromewebstore.google.com/detail/adguard-adblocker/bgnkhhnnamicmpeenaelnjfhikgbkllg). If you want to know when the release is coming, follow us on social media.

After the MV3 release, the old beta extension will be renamed to [AdGuard Ad Blocker MV2](https://chromewebstore.google.com/detail/adguard-adblocker-beta/gfggjaccafhcbfogfkogggoepomehbjl). We will continue to support it until Google phases it out

**Comment by emeritaacuity0u** [comment]
@vozersky, with that information, will the MV3 extension need to connect to the adtidy domain to update filters?

The company I'm in blocks the AdGuard adtidy domain.
At the moment I use the MV3 extension purely because it doesn't get blocked by company policy.

**Comment by vozersky** [comment]
@emeritaacuity0u nope, for now filters are updated together with the extension, no requests are sent to adtidy
