### ISSUE TITLE
Broad Host permissions 

### ISSUE THREAD

**Issue by Rutuj-Runwal** [AdguardTeam/AdGuardMV3#7]
The extension currently uses the host permissions of all urls
```
"host_permissions": [
      "<all_urls>"
    ],
```

Instead use of http://\*/\*", https://\*/\* or \*://\*/\* can be done as the all_urls matches any URL that starts with a permitted scheme (http:, https:, file:, or ftp:) but access to file: and ftp: is not required.

**Comment by LifeIsStrange** [comment]
The ability to use a content blocker for local html files (development) and for pdf with js (or hiding elements in pdf.js ux) are nice usecases so if there's no real tangible value behind those restrictions, let's not regress the scope of the app?
