### ISSUE TITLE
Ad showing on YouTube videos when opened in new tab

### ISSUE THREAD

**Issue by katherine-yu** [AdguardTeam/AdGuardMV3#8]
When I open videos from within YouTube, no ads show, but if I open a video in a new tab or visit from a site other than YouTube (example: a Google search), an ad will play at the beginning of the video (if monetized). Refreshing the page does not remove the ad. This issue does not occur for embedded videos, but does occur if I click on the video to watch in another tab.

I do not get this issue when using the regular AdGuard AdBlocker extension.

Chrome Version 105.0.5195.102
AG Version 0.3.11

**Comment by durianbusuk** [comment]
I had to combine this with Adblock for Youtube™ extension to properly stop youtube ads.

**Comment by ameshkov** [comment]
Known issue of the current implementation, no worries will be fixed rather soon.

**Comment by 105th** [comment]
@katherine-yu @durianbusuk I think we fixed this in version 0.3.14+. please try to update the extension and check youtube ads
